version: "3.9"
services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always 
    env_file: 
      - .env
    ports: 
      - 3306:3306
  wordpress:
    image: weblwabl/nginx_wp:3.0
    #build: .
    restart: always
    env_file: 
      - .env
    ports:
      - 9000:80
    depends_on: 
      - database

        


